# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: Containerfile.j2
# --------------------------------------------------------------------------

ARG BASE_VERSION=15.1
FROM ghcr.io/daemonless/base:${BASE_VERSION}

ARG FREEBSD_ARCH=amd64
ARG PACKAGES="dotnet8 expat fontconfig freetype2 fribidi gettext-runtime intel-media-sdk libarchive libass libdrm libexif libiconv libogg libtheora libva libvorbis libzvbi mbedtls3 ocl-icd opus pango sqlite3 tesseract"
ARG UPSTREAM_URL="https://api.github.com/repos/MediaBrowser/Emby.Releases/releases/latest"
ARG UPSTREAM_JQ=".tag_name"
ARG HEALTHCHECK_ENDPOINT="http://localhost:8096/System/Ping"

ENV HEALTHCHECK_URL="${HEALTHCHECK_ENDPOINT}"

# --- Metadata (Injected by Generator) ---
LABEL org.opencontainers.image.title="Emby" \
      org.opencontainers.image.description="Personal media server with apps on just about every device." \
      org.opencontainers.image.source="https://github.com/daemonless/emby" \
      org.opencontainers.image.url="https://emby.media/" \
      org.opencontainers.image.licenses="LicenseRef-Emby-EULA" \
      org.opencontainers.image.vendor="daemonless" \
      org.opencontainers.image.authors="daemonless" \
      io.daemonless.category="Media Servers" \
      io.daemonless.port="8096" \
      io.daemonless.volumes="/config" \
      org.freebsd.jail.allow.mlock="required" \
      io.daemonless.arch="${FREEBSD_ARCH}" \
      io.daemonless.upstream-url="${UPSTREAM_URL}" \
      io.daemonless.upstream-jq="${UPSTREAM_JQ}" \
      io.daemonless.healthcheck-url="${HEALTHCHECK_ENDPOINT}" \
      io.daemonless.packages="${PACKAGES}"

# Install runtime dependencies
RUN pkg update && \
    pkg install -y ${PACKAGES} && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

# Download and install Emby Server from upstream
RUN VERSION=$(fetch -qo - "${UPSTREAM_URL}" | jq -r "${UPSTREAM_JQ}") && \
    fetch -o /tmp/emby-server.pkg \
      "https://github.com/MediaBrowser/Emby.Releases/releases/download/${VERSION}/emby-server-freebsd15_${VERSION}_amd64.pkg" && \
    pkg add /tmp/emby-server.pkg && \
    mkdir -p /app && \
    echo "${VERSION}" > /app/version && \
    rm /tmp/emby-server.pkg && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

RUN pw usermod bsd -d /config
ENV HOME=/config

COPY root/ /

RUN chmod +x /etc/services.d/emby-server/run /healthz

# --- Expose (Injected by Generator) ---
EXPOSE 8096

# --- Volumes (Injected by Generator) ---
VOLUME /config